[project]
name = "try-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "django>=3.2,<3.3",
]

[dependency-groups]
dev = [
    "python-decouple>=3.8",
]
